### PR TITLE
AS-2452: EFP VPC setup

### PR DESCRIPTION
**Pull request by trinitronx**
Fixed a bunch of bugs in redshift & firehose modules so they work in the playbook

### CODE REVIEW

**Comment by trinitronx** [comment]
@LesBarstow: It appears that we do... from my testing, the JSON library itself doesn't know how to convert the nested datetime in a dict into JSON.

Error was:

```
TASK [Create RedShift Cluster] *************************************************
task path: /Users/jcuzella/src/rp/ops-ansible-playbooks/playbooks/efp-vpc/validate-redshift-firehose.yml:29
ESTABLISH LOCAL CONNECTION FOR USER: jcuzella
localhost EXEC ( umask 22 && mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1452550209.36-19737499972161 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1452550209.36-19737499972161 )" )
localhost PUT /tmp/tmphLjfYd TO /Users/jcuzella/.ansible/tmp/ansible-tmp-1452550209.36-19737499972161/redshift
localhost EXEC LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /Users/jcuzella/.ansible/tmp/ansible-tmp-1452550209.36-19737499972161/redshift
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/Users/jcuzella/.ansible/tmp/ansible-tmp-1452550209.36-19737499972161/redshift", line 2636, in <module>
    main()
  File "/Users/jcuzella/.ansible/tmp/ansible-tmp-1452550209.36-19737499972161/redshift", line 474, in main
    invocations[module.params.get('command')](module, redshift_conn)
  File "/Users/jcuzella/.ansible/tmp/ansible-tmp-1452550209.36-19737499972161/redshift", line 353, in create_cluster
    cluster=response
  File "/usr/lib64/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib64/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib64/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib64/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: datetime.datetime(2016, 1, 11, 22, 14, 56, 347000, tzinfo=tzlocal()) is not JSON serializable

fatal: [127.0.0.1 -> localhost]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"allow_version_upgrade": false, "backup_retention": 35, "cluster_type": "multi-node", "command": "create", "db_name": "auth_owner", "db_port": 5439, "maint_window": "mon:03:00-mon:03:30", "name": "efp-storage-playbook-testing", "node_type": "dc1.large", "num_nodes": 4, "parameter_group": "default.redshift-1.0", "password": "****", "public": true, "subnet": "efp-redshift", "username": "efpproduser", "vpc_security_groups": "sg-f516e193", "wait": true, "zone": "us-east-1a"}, "module_name": "redshift"}, "parsed": false}
```

I was able to reproduce the error by running the RedShift module with the `pdb` debugger, and trying to simply run `json.dumps( response )` resulted in the same error:

```
(Pdb) from pprint import pprint as pp
(Pdb) pp response
{u'Clusters': [{u'AllowVersionUpgrade': False,
                u'AutomatedSnapshotRetentionPeriod': 35,
                u'AvailabilityZone': 'us-east-1a',
                u'ClusterCreateTime': datetime.datetime(2016, 1, 12, 0, 38, 13, 852000, tzinfo=tzlocal()),
                u'ClusterIdentifier': 'efp-storage-playbook-testing',
                u'ClusterNodes': [{u'NodeRole': 'LEADER',
                                   u'PrivateIPAddress': '10.251.12.171',
                                   u'PublicIPAddress': '52.71.106.1'},
                                  {u'NodeRole': 'COMPUTE-0',
                                   u'PrivateIPAddress': '10.251.9.1',
                                   u'PublicIPAddress': '52.70.46.247'},
                                  {u'NodeRole': 'COMPUTE-1',
                                   u'PrivateIPAddress': '10.251.3.233',
                                   u'PublicIPAddress': '52.20.211.103'},
                                  {u'NodeRole': 'COMPUTE-2',
                                   u'PrivateIPAddress': '10.251.8.238',
                                   u'PublicIPAddress': '52.71.171.66'},
                                  {u'NodeRole': 'COMPUTE-3',
                                   u'PrivateIPAddress': '10.251.9.198',
                                   u'PublicIPAddress': '52.71.166.117'}],
                u'ClusterParameterGroups': [{u'ParameterApplyStatus': 'in-sync',
                                             u'ParameterGroupName': 'default.redshift-1.0'}],
                u'ClusterPublicKey': 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCNdH9cHIMXh9qtxhcog6nuWmBsLkjMgD05wDVKRoMV1YINysltR//y8GyzdewXhqjQLcGFwnvfJnb316wB63enZPXAR5jsxVq/x8CzkLznCJ2YV9IrQ4Nx70ycdnAxrI8FUM4FtdsTw/qMx6wNo2MEvNihMLowRzSfDTHxi2xdZdUWd0yQojfLuncdqxE9pK1muoTF3mkYFmXR0oL0NKrfnmSUr+tpxSn6mo7rzkVdA6ZDMdmPhvn4dZbfW6Vu5f2m5cDZLhIIQPnZ2EXs1Zre2tH5rGaQqcrj1vV8Yb62SPo9IplNkrcTiq52tuEYK7hdYKXGeCcDu2tNkMJJXkY5 Amazon-Redshift\n',
                u'ClusterRevisionNumber': '1012',
                u'ClusterSecurityGroups': [],
                u'ClusterStatus': 'available',
                u'ClusterSubnetGroupName': 'efp-redshift',
                u'ClusterVersion': '1.0',
                u'DBName': 'auth_owner',
                u'Encrypted': False,
                u'Endpoint': {u'Address': 'efp-storage-playbook-testing.cqyack4dtwyg.us-east-1.redshift.amazonaws.com',
                              u'Port': 5439},
                u'MasterUsername': 'efpproduser',
                u'NodeType': 'dc1.large',
                u'NumberOfNodes': 4,
                u'PendingModifiedValues': {},
                u'PreferredMaintenanceWindow': 'sat:04:30-sat:05:00',
                u'PubliclyAccessible': True,
                u'Tags': [],
                u'VpcId': 'vpc-9328f7f7',
                u'VpcSecurityGroups': [{u'Status': 'active',
                                        u'VpcSecurityGroupId': 'sg-f516e193'}]}],
 'ResponseMetadata': {'HTTPStatusCode': 200,
                      'RequestId': 'df1b578d-b8c4-11e5-8071-932ecb440557'}}

(Pdb) pp response['Clusters'][0]['ClusterCreateTime']
datetime.datetime(2016, 1, 12, 0, 38, 13, 852000, tzinfo=tzlocal())
(Pdb) import json
(Pdb) print json.dumps(response)
*** TypeError: datetime.datetime(2016, 1, 12, 0, 38, 13, 852000, tzinfo=tzlocal()) is not JSON serializable
```

The module was failing just after the cluster create, and failing on the returned nested `"Clusters"` dict which contained a list of a dict with nested `datetime` object within it.  This was different than the response in `_describe_cluster()`, which was a `"Cluster"` dict with nested `datetime` object within:

```
338  	        try:
339  ->	            waiter.wait(ClusterIdentifier=ClusterIdentifier)
340  	        except botocore.exceptions.WaiterError, e:
341  	            module.fail_json(msg='cluster cannot be found')
342
343 B	    response = conn.describe_clusters(
344  	        ClusterIdentifier=ClusterIdentifier
(Pdb) n
> /Users/jcuzella/.ansible/tmp/ansible-tmp-1452550209.36-19737499972161/redshift(343)create_cluster()
-> response = conn.describe_clusters(
(Pdb) pp response
{u'Cluster': {u'AllowVersionUpgrade': False,
              u'AutomatedSnapshotRetentionPeriod': 35,
              u'AvailabilityZone': 'us-east-1a',
              u'ClusterIdentifier': 'efp-storage-playbook-testing',
              u'ClusterParameterGroups': [{u'ParameterApplyStatus': 'in-sync',
                                           u'ParameterGroupName': 'default.redshift-1.0'}],
              u'ClusterSecurityGroups': [],
              u'ClusterStatus': 'creating',
              u'ClusterSubnetGroupName': 'efp-redshift',
              u'ClusterVersion': '1.0',
              u'DBName': 'auth_owner',
              u'Encrypted': False,
              u'MasterUsername': 'efpproduser',
              u'NodeType': 'dc1.large',
              u'NumberOfNodes': 4,
              u'PendingModifiedValues': {u'MasterUserPassword': '****'},
              u'PreferredMaintenanceWindow': 'sat:04:30-sat:05:00',
              u'PubliclyAccessible': True,
              u'Tags': [],
              u'VpcId': 'vpc-9328f7f7',
              u'VpcSecurityGroups': [{u'Status': 'active',
                                      u'VpcSecurityGroupId': 'sg-f516e193'}]},
 'ResponseMetadata': {'HTTPStatusCode': 200,
                      'RequestId': '19f2a043-b8c4-11e5-8ea1-e1625480dcbb'}}
```

**Comment by trinitronx** [comment]
The real issue here is that the `json` library does not know how to handle arbitrary nested objects like `datetime` (even if they're core lib object classes).  It does know how to handle most of the [basic language types][1].

I found [an example for using a custom encoder][3] to handle `datetime`, which would probably be a better way to solve the problem, however it did not handle nested `datetime` easily.  Not sure if that example was actually the right way to provide a [`default()` function encoder override][2] in our case, as it seemed to replace the entire `default` encoder function, and only handled a single top-level datetime object when calling `json.dumps`.  We would want one more robust that could handle both of these nested objects (i.e.: `dict -> list -> dict -> datetime`, `dict -> datetime`, or possibly any unknown generic nested object that Amazon may decide to throw back as a return in the future).

[1]: https://docs.python.org/2/library/json.html#py-to-json-table
[2]: https://docs.python.org/2/library/json.html#encoders-and-decoders
[3]: http://stackoverflow.com/questions/11875770/how-to-overcome-datetime-datetime-not-json-serializable-in-python

**Comment by trinitronx** [comment]
I figure that for now, the playbook works to create clusters & get the JDBC URL we need, so there's no need to worry about custom encoders or anything fancy.

**Comment by guildencrantz** [comment]
:+1:

**Pull request merged**
